using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Pepperi.SDK.Model.Fixed
{
    /// <summary>
    /// Note: This class is not generated by the Generator
    ///       Reason: metadata is not accurate
    /// </summary>
    public class UserDefinedTable
    {
        public Int64? InternalID { get; set; }
        public String MapDataExternalID { get; set; }
        public Boolean? Hidden { get; set; }
        public String MainKey { get; set; }
        public String SecondaryKey { get; set; }
        public List<String> Values { get; set; }
    }
}
