using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Pepperi.ModelGenerator.Model.Common
{
    /// <summary>
    /// represents the name of the generated class
    /// </summary>
    internal enum eModelClassName
    {
        Account,
        AccountCatalog,
        AccountInventory,
        AccountUser,
        Activity,
        Catalog,
        Contact,
        Inventory,
        Item,
        ItemDimensions1,
        ItemDimensions2,
        ItemPrice,
        PriceList,
        SpecialPriceList,
        Transaction,
        TransactionLine,
        User, 
        //UserDefinedTable  -   The model class is not generated by the generator (Reason: the metadata is not accurate.)
    };
}
